
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;

	private global::Gtk.Button button12;

	private global::Gtk.Table table2;

	private global::Gtk.Button altı;

	private global::Gtk.Button beş;

	private global::Gtk.Button dokuz;

	private global::Gtk.Button dört;

	private global::Gtk.Button sekiz;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Button iki;

	private global::Gtk.Button sıfır;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Button üç;

	private global::Gtk.Button virgül;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Button bir;

	private global::Gtk.Button yedi;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("hesaP");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.button12 = new global::Gtk.Button();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table1.Add(this.button12);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.button12]));
		w1.TopAttach = ((uint)(1));
		w1.BottomAttach = ((uint)(2));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.altı = new global::Gtk.Button();
		this.altı.CanFocus = true;
		this.altı.Name = "altı";
		this.altı.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table2.Add(this.altı);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.altı]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.beş = new global::Gtk.Button();
		this.beş.CanFocus = true;
		this.beş.Name = "beş";
		this.beş.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table2.Add(this.beş);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.beş]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.dokuz = new global::Gtk.Button();
		this.dokuz.CanFocus = true;
		this.dokuz.Name = "dokuz";
		this.dokuz.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table2.Add(this.dokuz);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.dokuz]));
		w4.LeftAttach = ((uint)(2));
		w4.RightAttach = ((uint)(3));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.dört = new global::Gtk.Button();
		this.dört.CanFocus = true;
		this.dört.Name = "dört";
		this.dört.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table2.Add(this.dört);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2[this.dört]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.sekiz = new global::Gtk.Button();
		this.sekiz.CanFocus = true;
		this.sekiz.Name = "sekiz";
		this.sekiz.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table2.Add(this.sekiz);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.sekiz]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.iki = new global::Gtk.Button();
		this.iki.CanFocus = true;
		this.iki.Name = "iki";
		this.iki.Label = global::Mono.Unix.Catalog.GetString("2");
		this.vbox1.Add(this.iki);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.iki]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.sıfır = new global::Gtk.Button();
		this.sıfır.CanFocus = true;
		this.sıfır.Name = "sıfır";
		this.sıfır.Label = global::Mono.Unix.Catalog.GetString("0");
		this.vbox1.Add(this.sıfır);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.sıfır]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.table2.Add(this.vbox1);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox1]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.üç = new global::Gtk.Button();
		this.üç.CanFocus = true;
		this.üç.Name = "üç";
		this.üç.Label = global::Mono.Unix.Catalog.GetString("3");
		this.vbox2.Add(this.üç);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.üç]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.virgül = new global::Gtk.Button();
		this.virgül.CanFocus = true;
		this.virgül.Name = "virgül";
		this.virgül.Label = global::Mono.Unix.Catalog.GetString(",");
		this.vbox2.Add(this.virgül);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.virgül]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.table2.Add(this.vbox2);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox2]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.bir = new global::Gtk.Button();
		this.bir.CanFocus = true;
		this.bir.Name = "bir";
		this.bir.Label = global::Mono.Unix.Catalog.GetString("1");
		this.vbox3.Add(this.bir);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.bir]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		this.table2.Add(this.vbox3);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox3]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.yedi = new global::Gtk.Button();
		this.yedi.CanFocus = true;
		this.yedi.Name = "yedi";
		this.yedi.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table2.Add(this.yedi);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2[this.yedi]));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add(this.table2);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.table2]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.table1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
